### PR TITLE
feat : adding support to lilygo s3 amoled touch 78khs & waveshare ESP32-S3-GEEK dongle 78khs  & weact ESP32-D0WD-V3 57khs  & wemos s2 mini 38khs fixes #202 and disable/enable led on no display board

### LINKED ISSUE #202: [Feature] ESP32-S2FN4R2 (aka Lolin S2 mini) support
Dear,

Could someone handle ESP32-S2FN4R2 please ?

It's a cheap and widespread ESP32-S2 module. It would be nice to have NerdMiner V2 on it.
Thank you in advance.

### PR DESCRIPTION
**Pull request by julio-matarranz**
adding support to lilygo s3 amoled touch 78khs
adding support to waveshare ESP32-S3-GEEK dongle 78khs
adding support to weact ESP32-D0WD-V3 57khs 
adding wemos s2 mini 38khs fixes #202
disable/enable led on no display board
update supported board documentation
adding firmwares

### CODE REVIEW

**Comment by julio-matarranz** [comment]
Dear @BitMaker-hub possible conflicts with #323

**Comment by julio-matarranz** [comment]
Dear @BitMaker-hub, could you look at that PR mlese ? 🙏🏻

**Comment by julio-matarranz** [comment]
image

**Comment by julio-matarranz** [comment]
image

**Comment by Leonardoal26** [comment]
Hello, what files did you use to configure this board? I have not been able to see the screen after flashing

**Comment by julio-matarranz** [comment]
> Hello, what files did you use to configure this board? I have not been able to see the screen after flashing

Dear @Leonardoal26, did you try flashing with "bin/bin LILYGO TDisplay-AMOLED-TOUCH" files ?!

**Comment by Leonardoal26** [comment]
No, I'm trying the esp32 s3 geek board, is it the same as the amoled?

**Comment by julio-matarranz** [comment]
> No, I'm trying the esp32 s3 geek board, is it the same as the amoled?

@Leonardoal26 No there is a firmware directory for each board 😉

**Comment by julio-matarranz** [comment]
> No, I'm trying the esp32 s3 geek board, is it the same as the amoled?

@Leonardoal26 did you manage using your S3 Geek with "bin/bin Waveshare S3 Geek/0x10000_firmware.bin" and other files inside "bin/bin Waveshare S3 Geek" directory ?

**Comment by BitMaker-hub** [comment]
@julio-matarranz Amazing work!
Sorry for not being here to follow this work, this is fabulous

I'll merge it right now

**Review by BitMaker-hub — APPROVED** [review]

**Comment by julio-matarranz** [comment]
> @julio-matarranz Amazing work!
> 
> Sorry for not being here to follow this work, this is fabulous
> 
> 
> 
> I'll merge it right now
> 
> 

Thank you for the merge ☺️

**Pull request merged**
