### PR TITLE
Added support for another ESP32_2432S028 variant.

### PR DESCRIPTION
**Pull request by paelzer**
Hello

Related to discussion: https://github.com/BitMaker-hub/NerdMiner_v2/discussions/273

I have added support for another variant of ESP32_2432S028. There are several different boards available and some need to have different settings than others. 
This changes work at least fine with my variant, which is different from others, as for example, it has micro USB and USB-C connector. 

Unfortunately I only have this one which I can use for testing:

image

As mentioned earlier, I don't have professional programming background so I'm not sure, if the way I implemented it, is ok, even if it works fine :-)

Boris

### CODE REVIEW

**Comment by sany3001** [comment]
I will try your code with my board. Seems to be same as yours, but who knows really. :-)
I guess I can switch to your fork, build it and flash it.

**Comment by sany3001** [comment]
Thanks for quick fix, already building! :+1:

**Comment by paelzer** [comment]
Hi, not yet done. I still try to figure out what change from Friday caused it to stop working.
Will look into it again later.

**Comment by sany3001** [comment]
Colors are OK! But content on display corresponds to regular miner. With some missing data.
Keep updated your tester. :-)

unnamed

**Comment by sany3001** [comment]
Flashed again and it looks good now

unnamed (1)

**Comment by sany3001** [comment]
So it is not about flashing device, it is about boot. Sometimes you get the statistics and the pool info, sometimes you don't.

**Comment by paelzer** [comment]
@sany3001 Hello, just a question... did you using Linux when the compiling failed in your screenshot above?

**Comment by sany3001** [comment]
Yes, all trials in Linux Mint.

**Comment by paelzer** [comment]
@sany3001 OK, that was my guess, could you please try again with this 2nd branch I created, if you find some time:

image

It should work. I successfully tested with Ubuntu but should of course work with Mint as well.
I just added pin defines for SD card slot to have the SD card slot working. But to be able to compile under Linux I also had to replace back slashes by forward slashes in "SDCard.h". I found this information in the screenshot you posted:

image

**Comment by sany3001** [comment]
`master` and `add-SD-card-pin-defines-for-ESP32_2432S028` are both buildable for me.

I have flashed `add-SD-card-pin-defines-for-ESP32_2432S028` and the final result is the same - pool info is not always available. Colors are ok.

**Review by BitMaker-hub — APPROVED** [review]
Fantastic thanks

**Comment by 68gt500** [comment]
I also just received the new variant, with the added USB-C connector.
Two issues
1 - When compiling with tft_espi the display is inverted - need to add:
 tft.invertDisplay(1);
That fixes that issue.
2 - on the original the blue RGB LED would be always on - fixed that with digitalWrite(16, LOW);
 on the new variant the green RGB LED is always on, but neither setting 16, or 17 low seems to help. 
 
 Any ideas ?

**Comment by HenrysCat** [comment]
>display is inverted - need to add: tft.invertDisplay(1); That fixes that issue.

Where do I add this?

I have followed info here https://github.com/BitMaker-hub/NerdMiner_v2/discussions/273 and edited the files, flashed and still get inverted colours?

**Comment by 68gt500** [comment]
@HenrysCat: 
The inverted display can be corrected in either of 2 places:
- in the tft_espi library configuration file adding a line: #define TFT_INVERSION_ON
- alternatively in the setup portion of the code adding: tft.invertDisplay(1);

**Comment by paelzer** [comment]
@HenrysCat 

Hello

In case of the ESP32_2432S028 version with USB-C and micro USB...

If you use the current Nerd Miner version no more manual adjustment in the code should be needed anymore, to fix the color setup, if you just select "ESP32_2432S028_2USB" as env in the bottom bar before building, since the fix is already implemented in the source code.

image

Boris

**Comment by HenrysCat** [comment]
Ah I see now, this is not just editing files is it, I need to build in Visual Studio? I have it installed but never used it, this may be beyond me, is there any way to get .bin files already built with the required changes?

**Comment by sany3001** [comment]
> Ah I see now, this is not just editing files is it, I need to build in Visual Studio? I have it installed but never used it, this may be beyond me, is there any way to get .bin files already built with the required changes?
 
It shall be really easy to build and flash. Please check this: https://github.com/BitMaker-hub/NerdMiner_v2/issues/306#issuecomment-1959131743
If needed, we can add more info there.

**Comment by djcasper1975** [comment]
thankyou i have done this with no experience by your helps here.

**Comment by denvee32** [comment]
is there a .bin out there to just flash it for those of us that are not programmers? Please and thanks.
i have tried the bins from the fork [NerdMiner_v2_twoUSB_support] but it still not in dark mode. tried the latest bin here in the main build no go

**Comment by 19201003080114** [comment]
https://flasher.bitronics.store/

**Comment by 19201003080114** [comment]
Try to flash the bin using https://espressif.github.io/esptool-js/

**Comment by HenrysCat** [comment]
> is there a .bin out there to just flash it for those of us that are not programmers? 

[Here](https://send.internxt.com/download/598af47e-652c-4956-affb-3e28bce6e0fe?code=cd33881921130b7cc524f433a398e7ad148a8f20d8ed140ecb24c26d2d6671d0)

**Comment by denvee32** [comment]
> > is there a .bin out there to just flash it for those of us that are not programmers?
> 
> [Here](https://send.internxt.com/download/598af47e-652c-4956-affb-3e28bce6e0fe?code=cd33881921130b7cc524f433a398e7ad148a8f20d8ed140ecb24c26d2d6671d0)

BOOM.. thanks!!!!!

**Comment by RahulP0529** [comment]
> > > is there a .bin out there to just flash it for those of us that are not programmers?
> > 
> > 
> > [Here](https://send.internxt.com/download/598af47e-652c-4956-affb-3e28bce6e0fe?code=cd33881921130b7cc524f433a398e7ad148a8f20d8ed140ecb24c26d2d6671d0)
> 
> BOOM.. thanks!!!!!

Can you resend?

**Pull request merged**
