### PR TITLE
add new device T-QT for smaller lcd

### PR DESCRIPTION
**Pull request by metalnow**
1. merged T-QT for 128 x 128 resolution of small screen device 
2. update and merge new version of TFT_eSPI lib 
3. add 3d printed files of stl 
4. update precompiled firmware 
5. add board definition of esp32-s3-t-qt

### CODE REVIEW

**Comment by BitMaker-hub** [comment]
Thanks MetalNow, please can you make changes to add new board after the incomming board abstraction?
I'll just merge it now to let you enter it

**Comment by BitMaker-hub** [comment]
MetalNow, can you rebase your changes to the new dev branch state. Now is more easy to add any board.
I see you did a great job, and I'm sorry to make you do more but will be better for standaritzation

**Comment by metalnow** [comment]
no problem

**Comment by BitMaker-hub** [comment]
thanks

**Comment by BitMaker-hub** [comment]
@metalnow please, make new PR with rebased code ok?

**Comment by metalnow** [comment]
Yes. sure. Will make new pr in this weekend.

**Pull request closed without merging**
