### PR TITLE
move libs to common and clean platform config file

### PR DESCRIPTION
**Pull request by valerio-vaccaro**
move libs to common directory, in that way we don't need to compile libs if are not used plus some cleaning on configuration file

### CODE REVIEW

**Comment by romanmashta** [comment]
Wouldn't it be better to use  `lib_ignore` config parameter and left PlatformIO standard folder structure?
example:
`lib_ignore = rm67162, TFT_eSPI@2.5.23`
will ignore local libraries

**Comment by romanmashta** [comment]
Yes, but that's the purpose of Lib folder. And that's how PlatformIO saw this by design, and why lib_ignore option exists

**Comment by valerio-vaccaro** [comment]
Are you sure about your statement on global libraries?

**This option is DEPRECATED. We do not recommend using global libraries for new projects. Please use a declarative approach for the safety-critical embedded development and declare project dependencies using the [lib_deps](https://docs.platformio.org/en/stable/projectconf/sections/env/options/library/lib_deps.html#projectconf-lib-deps) option**

https://docs.platformio.org/en/stable/projectconf/sections/platformio/options/directory/globallib_dir.html

**Comment by romanmashta** [comment]
If this folder is deprecated, why it is part of new empty project for latest platform.io? 

Screenshot 2023-09-15 at 16 09 47

Again, tossing around half thousand files vs adding 10 lines in config also does not looks right.

**Comment by valerio-vaccaro** [comment]
platformio suggest this changes and I agree, anyway I will not push more this topic and maintain my fork

**Comment by BitMaker-hub** [comment]
I don't know what to do with this PR but I agree is confusing to have libs_env and then the global lib folder.

Even this, how is afecting moving it to common folder? In fact, each board is picking his own TFT lib

**Comment by Jason2866** [comment]
> Are you sure about your statement on global libraries?
> 
> **This option is DEPRECATED. We do not recommend using global libraries for new projects. Please use a declarative approach for the safety-critical embedded development and declare project dependencies using the [lib_deps](https://docs.platformio.org/en/stable/projectconf/sections/env/options/library/lib_deps.html#projectconf-lib-deps) option**
> 
> https://docs.platformio.org/en/stable/projectconf/sections/platformio/options/directory/globallib_dir.html

You are mixing things. `globallib_dir` is a different setting. The used and recommended is https://docs.platformio.org/en/stable/projectconf/sections/platformio/options/directory/lib_dir.html

**Comment by valerio-vaccaro** [comment]
looks like nobody care about it, closing sadly

**Pull request closed without merging**
