### PR TITLE
Miner cosmetics

### PR DESCRIPTION
**Pull request by golden-guy**

### CODE REVIEW

**Comment by rudikx6** [comment]
Hi Arne, 

i tried your code changes in the 3 files for successful submits. and i could not see any changes in the console.
maybe my expactaition is wrong. Is the STRATUM_SUCCESS only printed if the hash would fund? or must it be regulary printed in the console?

I tried it with the solo.ckpool and for testing with this nerdminer pool from CHMEX.

But maybe my expactation is wrong becuase for now I am not so familiar with this stratum things. 

Greetings from Germany, Rudi :)

**Comment by golden-guy** [comment]
Who is Arne? :) Other than that, are you running a build from dev branch?

**Comment by rudikx6** [comment]
XD.... i don´t know who Arne is. 
My mistake,  sorry Steffan D

No, i simply make the changes in the files of the 1.5.2 branch. 
Ok. i will try to use the dev branch. Need to learn how to load this XD...

**Comment by rudikx6** [comment]
Hi Stefan,

now i was able to compile from dev banch :)
The STARTUM succsess message is comming only one time. 
Is it only a positiv response for the registation on the pool? Is this correct?

What iam not understanding is the message "MINER WORK ABORTED"  is it because the pool sends new instructions?




[WORKER] ==> Autorize work
                            Sending  : {"params": ["1NrVkVpagsdbLrK7uuP1SWwB1JibA3Aohs", "x"], "id": 2, "method": "mining.authorize"}

  Sending  : {"id": 3, "method": "mining.suggest_difficulty", "params": [0.0001]}
                                                                                   Received message from pool
  Receiving: {"params":[10000],"id":null,"method":"mining.set_difficulty"}
    Parsing Method [SET DIFFICULTY]
    difficulty: 10000.000000000000
  Received message from pool
  Receiving: {"params":["6485163800023a86","e4ae4ae37ba87e9ecc72d772c041f6d5433a53480003b65c0000000000000000","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503e9370c000436c3c4640481bc1b070c","0a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff032ddf5c25000000001976a914efb705d8701b532ac03d0dc43a31472705dfb6d188ac9333c3000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed1e778696fbaabbe66f01694f3f6f95bd770635e59713e8b8470d734aca5fb41a00000000",["d73084402e771409cfedd4716d332f5fb20e5447fdb5fbbaed4a1a9ab0633675","afe1ec25be29dde58f3484398b9d4d1402f439bf4eeb3beb8aed60b4b8c16a0e","5cd3e8d45ea853f2b334cc20b60695a4a579b1338b9bc2c08efcf9038a18765e","1bb1e9d95461b16cb19dec7e7012232ce2ced3ad198af4537ead8b94f828d29d","1373f5c9e01983e3964d126b23dd7515dc0ca7ed5de2ce98b9a7e82de729e76d","c4101f518b2ce2a46e2b2761711326232fc246e59006d77ba8e730bb05b721c6","c818025bb1652a0f17ac5f61fcb126f15e41a1ee9fa8c5c59f9292a1402f7f5f","fa831736b95f4de6496586dd903ae7715494d9de4b01bd7d0cf8a666597fe902","5cfd65e2b6e6388d4ac9623ddf443e27e4bd514e75fbe4daa0e1ffe44b25a9eb","fce412138e08db3d6e77bcaa469deb982a3fad33566374cdff9509d034a80986","53891f3b1e2e8e72ea00a813f93d4683bb44875fca8743866db439f5303e4fd0","347835837520876f7bf829c74d04c638dc9e7de2bd8ccf14d0ef42cefa94ed18"],"20000000","17056102","64c4c336",true],"id":null,"method":"mining.notify"}
    Parsing Method [MINING NOTIFY]
    target: 0000000000000000000561020000000000000000000000000000000000000000
    coinbase: 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503e9370c000436c3c4640481bc1b070c5e00596600000000000000010a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff032ddf5c25000000001976a914efb705d8701b532ac03d0dc43a31472705dfb6d188ac9333c3000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed1e778696fbaabbe66f01694f3f6f95bd770635e59713e8b8470d734aca5fb41a00000000
    merkle sha         : ee28bf5b444ad060b3de16370c2c31a626b243bc2875ad462e8e2a148ddf1aec
  Received message from pool
  Receiving: {"params":[10000],"id":null,"method":"mining.set_difficulty"}
    Parsing Method [SET DIFFICULTY]
    difficulty: 10000.000000000000
  Received message from pool
  Receiving: {"result":true,"error":null,"id":2}
 **Parsed JSON: Success**
>>> STARTING TO HASH NONCES
>>> STARTING TO HASH NONCES
>>> Completed 0 share(s), 22 Khashes, avg. hashrate 19.49 KH/s
                                                              >>> Completed 0 share(s), 70 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                            >>> Completed 0 share(s), 118 Khashes, avg. hashrate 43.84 KH/s
                                                                                                                                                                                           >>> Completed 0 share(s), 166 Khashes, avg. hashrate 43.84 KH/s
                                                                                                                                                                                                                                                          >>> Completed 0 share(s), 214 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                                                                                                                                                                                                                         >>> Completed 0 share(s), 262 Khashes, avg. hashrate 43.84 KH/s
                                                           >>> Completed 0 share(s), 310 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                          >>> Completed 0 share(s), 358 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                                                                                         >>> Completed 0 share(s), 407 Khashes, avg. hashrate 44.75 KH/s
                                                                                                                                                                                                                                                        >>> Completed 0 share(s), 455 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                                                                                                                                                                                                                       >>> Completed 0 share(s), 503 Khashes, avg. hashrate 43.84 KH/s
                                                         >>> Completed 0 share(s), 551 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                        >>> Completed 0 share(s), 600 Khashes, avg. hashrate 44.79 KH/s
                                                                                                                                                                                       >>> Completed 0 share(s), 648 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                                                                                                                                                      >>> Completed 0 share(s), 696 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                                                                                                                                                                                                                       Received message from pool
  Receiving: {"params":["6485163800023a87","e4ae4ae37ba87e9ecc72d772c041f6d5433a53480003b65c0000000000000000","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503e9370c000454c3c464040d8dd0060c","0a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff038d165e25000000001976a914efb705d8701b532ac03d0dc43a31472705dfb6d188aced39c3000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed22611550c912b4fd4efa9c2cef01f95f2d4f5b887b1524f4fefb499b43b18ab600000000",["d73084402e771409cfedd4716d332f5fb20e5447fdb5fbbaed4a1a9ab0633675","afe1ec25be29dde58f3484398b9d4d1402f439bf4eeb3beb8aed60b4b8c16a0e","5cd3e8d45ea853f2b334cc20b60695a4a579b1338b9bc2c08efcf9038a18765e","1bb1e9d95461b16cb19dec7e7012232ce2ced3ad198af4537ead8b94f828d29d","1373f5c9e01983e3964d126b23dd7515dc0ca7ed5de2ce98b9a7e82de729e76d","c4101f518b2ce2a46e2b2761711326232fc246e59006d77ba8e730bb05b721c6","a010a0ae62f799da575c5b4f90e21806c67739b6535801d134050ee55b36d65a","4a72e342504dd58be1958adc7e1b52f44612788a63b772b90bfcea9fbd1137f3","259bca1bc8490be5ceac9e306f35c75867471536016b90c0519c366ba0e22e62","87b9f80ac349413f92e78ebb6c1283d3b81892f3066907c352a5dcc60518d211","683ce18d7a7b2e923e0322d6513d2465aa62a0a88c63249d1a91285260a193f8","999f1365d9318ab897273feeb79fe7e9fae2f39883a128c784fec246ceaac0c6"],"20000000","17056102","64c4c354",false],"id":null,"method":"mining.notify"}
    Parsing Method [MINING NOTIFY]
**MINER WORK ABORTED** >> waiting new job
>>> Finished job waiting new data from pool>>> Resetting watchdog timerMINER WORK ABORTED >> waiting new job    target:
>>> Finished job waiting new data from pool0000000000000000000561020000000000000000000000000000000000000000
>>> Resetting watchdog timer    coinbase: 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503e9370c000454c3c464040d8dd0060c5e00596600000000000000020a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff038d165e25000000001976a914efb705d8701b532ac03d0dc43a31472705dfb6d188aced39c3000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed22611550c912b4fd4efa9c2cef01f95f2d4f5b887b1524f4fefb499b43b18ab600000000
    merkle sha         : e7c6eb5e70852bea81c1d1e000301c5d8f9ac10042c1bb85b9f1d5b6ab925911
>>> STARTING TO HASH NONCES
>>> STARTING TO HASH NONCES
>>> Completed 0 share(s), 739 Khashes, avg. hashrate 39.27 KH/s
                                                               >>> Completed 0 share(s), 787 Khashes, avg. hashrate 43.88 KH/s
                                                                                                                              >>> Completed 0 share(s), 835 Khashes, avg. hashrate 43.84 KH/s
                                                                                                                                                                                             >>> Completed 0 share(s), 883 Khashes, avg. hashrate 43.84 KH/s
                                                                                                                                                                                                                                                            >>> Completed 0 share(s), 931 Khashes, avg. hashrate 43.84 KH/s
                                                                                                                                                                                                                                                                                                                           >>> Completed 0 share(s), 980 Khashes, avg. hashrate 44.75 KH/s
                                                             >>> Completed 0 share(s), 1028 Khashes, avg. hashrate 43.80 KH/s
                                                                                                                             >>> Completed 0 share(s), 1076 Khashes, avg. hashrate 43.76 KH/s

**Comment by golden-guy** [comment]
Looks all fine to me. I guess this is ckpool? You see that the pool sets a very high start diff (10000), which the NM won't submit a valid hash for anytime soon. This stratum_success message doesn't mean you have hit a block or anything, but rather that the request from the miner has been processed successfully by the pool.
And, indeed, if the pool sends new work, the miner picks it up and instantly aborts the current work. That's what you see in the logs then.

**Comment by BitMaker-hub** [comment]
Exactly as Steffan says, the miner aborted log means current job work is stopped to not create stale shares.

**Pull request merged**
