### PR TITLE
feature: add lilygo t-hmi duex

### PR DESCRIPTION
**Pull request by cosmicpsyop**
- add  lilygo t-hmi 
- add fees bottom panel
- experimented with price in bottom title
- touch screen not enabled
- screen advance: mining (pool), clock (fees), global(fees), price (pool)
- button function left to right : b1 (advance screen) b2 (reset) b3 (none)  usb-c side
- diagram: https://www.electronics-lab.com/wp-content/uploads/2023/07/T-HMI-Pinout-Diagram-850x758.webp
- thanks for the graphic assistance  @nitroxgas 
22222IMG_20240123_215510
I11111MG_20240123_221837

### CODE REVIEW

**Comment by BitMaker-hub** [comment]
Hi, this is really cool. thanks

**Comment by Leonardoal26** [comment]
Hello, what files did you use to configure this board? I have not been able to see the screen after flashing

**Comment by cosmicpsyop** [comment]
hey. thanks for taking a look. it is very possible i missed something along the way. when i got in a bind i reflashed the original factory app that the device was delivered with and then overwrite NerdminerV2 firmware.  i am using the esptool.py to flash.  my port is  /dev/ttyACM0 .  yours may be different.
```
git clone https://github.com/Xinyuan-LilyGO/T-HMI.git
cd T-HMI/examples/factory/
```
after building, find the artifacts, and flash factory app
```
cd .pio/build/debug
esptool.py --port /dev/ttyACM0 erase_flash
esptool.py --port /dev/ttyACM0 write_flash 0x0 bootloader.bin 0x8000 partitions.bin 0x10000 firmware.bin 
```
after building flash NerdminerV2 firmware
```
cd NerdMiner_v2/.pio/build/NerdminerV2-T-HMI
esptool.py --port /dev/ttyACM0 write_flash 0x10000 firmware.bin 

```

**Comment by Leonardoal26** [comment]
Thanks for responding, where can I get the bin files you used for this board?

**Review by BitMaker-hub — APPROVED** [review]
Checked! Thanks for your contribution

**Comment by Leonardoal26** [comment]
Hello, what are the bin files for this board? I'm new to this and I'm a little confused.

**Comment by Leonardoal26** [comment]
Hi, can you please share the bin files?

**Comment by julio-matarranz** [comment]
> Hi, can you please share the bin files?

Dear,
You can check this : https://github.com/BitMaker-hub/NerdMiner_v2/releases/tag/nerdminer-prerelease-V1.6.4

**Pull request merged**
