### PR TITLE
Full lottery mining feature proposal

### PR DESCRIPTION
**Pull request by romanmashta**
### Full lottery mining proposal. 
User configurable option to mine with random nonce, default is off. Due to low hash rate it will never pass full nonce range, as alternative nonce can be random number on every iteration. Random nonce are split between thread for odds and even numbers

Screenshot 2023-09-13 at 23 48 08

### CODE REVIEW

**Comment by BitMaker-hub** [comment]
I like adding features but.. even this is fun and well coded I think could be uneficient. It exists the posibility to repeat a nonce. And don't know how affects hashrate

**Comment by romanmashta** [comment]
There is no performance impact. But not a problem. I'm just sharing features that I'm playing with.

**Comment by BitMaker-hub** [comment]
Hey romanmashta, why just add it and provide this as description, can you change it?
[] Random nonce mode. Use random nonces instead of incremental nonce mining (Experimental/No hashrate impact)

**Comment by BitMaker-hub** [comment]
I close it for the moment

**Pull request closed without merging**
