### PR TITLE
Solution to the odd colors in new boards version (work on any variant), and some improvements.

### PR DESCRIPTION
**Pull request by nitroxgas**
Color inversion as a parameter in settings;
WIFIManager adjustments;
Memory fine tuning (inconsistent sprite creation);
Price text size adjust;
Testnet banner if pointing to tn.vkbit.com;
SDCard tested and adjusted.
WhatsApp Image 2024-05-04 at 19 55 56
WhatsApp Image 2024-05-04 at 19 52 56

### CODE REVIEW

**Comment by nitroxgas** [comment]
Issues:
Display of Bitcoin-Price is cut off on the last digit / not showing correctly #377
Bad graphics using ESP32-24325028 #306
ERROR: *wm:[ERROR] parameter IDs can only contain alpha numeric chars #249
Password is hardcoded #219

**Comment by nitroxgas** [comment]
Issues:
ESP32-2432S028R 2,8" - Color Layout #273

**Comment by BitMaker-hub** [comment]
Absolutely amazing George, I'll try to merge this week. 
I'm doing some new job too.

**Comment by emanuelnatal** [comment]
olá boa tarde a todos a nova versão para a placa esp32-2432s28 com problema de inversão de cores, alguem pode me enviar o binário atualizado por e-mai?   emanuelnatal@gmail.com, desde já agradeço.

**Comment by OctaMiner** [comment]
Hello everyone, has the update been released yet? :)

**Comment by BitMaker-hub** [comment]
Hello George, can you rebase the code. then I'll be able to merge, please

**Pull request merged**
