### PR TITLE
feat : add support to c3 devices (mini ai-c3 and c3 super mini, 24khs) and refactor rgb led devices

### PR DESCRIPTION
**Pull request by julio-matarranz**
add support to c3 devices (for fun to test/challenge the new boards I have received) :
* c3 mini dual usb : tested on ai-c3 => 24kh/s
* c3 super mini : tested => 24kh/s

I made some refactoring too on RGB led boards to reduce number of files

### CODE REVIEW

**Comment by gyengus** [comment]
I tested this on ESP32 C3 SuperMini board. It works, but the led is on the GPIO8 pin.

**Comment by julio-matarranz** [comment]
> I tested this on ESP32 C3 SuperMini board. It works, but the led is on the GPIO8 pin.

Thank you for feedback. ☺️
Should be good now. I don't have the C3 super mini anymore, may you test it please ?

**Comment by gyengus** [comment]
> > I tested this on ESP32 C3 SuperMini board. It works, but the led is on the GPIO8 pin.
> 
> @gyengus Thank you for feedback. ☺️ Should be good now. I don't have the C3 super mini anymore, may you test it please ?

It works. Thank you.

**Comment by julio-matarranz** [comment]
> > > I tested this on ESP32 C3 SuperMini board. It works, but the led is on the GPIO8 pin.
> 
> > 
> 
> > @gyengus Thank you for feedback. ☺️ Should be good now. I don't have the C3 super mini anymore, may you test it please ?
> 
> 
> 
> It works. Thank you.

You are welcome, thanks for the test 😉

**Comment by BitMaker-hub** [comment]
Thank you guys for this job

**Comment by julio-matarranz** [comment]
> Thank you guys for this job

You are welcome ☺️

**Review by BitMaker-hub — COMMENTED** [review]
perfect!

**Review by BitMaker-hub — APPROVED** [review]

**Pull request merged**
