### PR TITLE
port to m5stack core and wt32-sc01, wt32-sc01-plus

### PR DESCRIPTION
**Pull request by valerio-vaccaro**
m5stack core based nerdmner reusing the graphics of the first han solominer

### CODE REVIEW

**Comment by valerio-vaccaro** [comment]
|Environment       |Status|Duration|
|------------------------|--------|------------|
|M5Stick-C                 |SUCCESS|   00:01:35.896|
|ESP32-S3-mini-wemos       |SUCCESS|   00:01:11.620|
|han_m5stack               |SUCCESS|   00:00:50.806|
|ESP32-S3-mini-weact       |SUCCESS|   00:00:53.631|
|ESP32-S3-devKitv1         |SUCCESS|   00:00:46.520|
|NerminerV2                |SUCCESS|   00:00:51.208|
|ESP32-devKitv1           | SUCCESS|   00:00:49.333|
|NerminerV2-S3-AMOLED      |SUCCESS|  00:01:09.167|
|NerminerV2-S3-DONGLE      |SUCCESS|   00:01:01.013|
|esp32cam                  |SUCCESS|   00:01:02.484|
|NerminerV2-T-QT           |SUCCESS|   00:01:05.454|
|ESP32-2432S028R           |SUCCESS|   00:01:09.106|
|NerdminerV2-T-Display_V1 |SUCCESS|   00:01:07.042|
|M5-StampS3                |SUCCESS |  00:01:12.415|

**Comment by julio-matarranz** [comment]
Sorry to ask but why mixing Han solo miner and Nerdminer in the same projet ?

**Comment by valerio-vaccaro** [comment]
Added support for **wt32-sc01** and **wt32-sc01-plus**.

|Environment               |Status|    Duration|
|------------------------|--------|------------|
|M5Stick-C                 |SUCCESS|   00:00:54.961|
|wt32-sc01                 |SUCCESS|   00:01:48.148|
|wt32-sc01-plus            |SUCCESS|   00:01:38.173|
|ESP32-S3-mini-wemos       |SUCCESS|   00:00:59.252|
|han_m5stack               |SUCCESS|   00:01:00.339|
|ESP32-S3-mini-weact       |SUCCESS|   00:01:02.783|
|ESP32-S3-devKitv1         |SUCCESS|   00:01:00.503|
|NerminerV2                |SUCCESS|   00:01:01.958|
|ESP32-devKitv1            |SUCCESS|   00:00:56.249|
|NerminerV2-S3-AMOLED      |SUCCESS|   00:01:06.481|
|NerminerV2-S3-DONGLE      |SUCCESS|   00:00:52.664|
|esp32cam                  |SUCCESS|   00:00:48.005|
|NerminerV2-T-QT           |SUCCESS|   00:00:59.300|
|ESP32-2432S028R           |SUCCESS|   00:01:02.000|
|NerdminerV2-T-Display_V1  |SUCCESS|   00:00:57.819|
|M5-StampS3                |SUCCESS|   00:00:46.805|

**Comment by valerio-vaccaro** [comment]
> Sorry to ask but why mixing Han solo miner and Nerdminer in the same projet ?

Nerdminer was based on hansolominer code, I personally avoid forks in project, if 90% of code is similar why forking a codebase.

When @BitMaker-hub decided to fork it behaved in a strange way compared to the open source world (among other things repeated for the flasher, as you can see the fork still lacks the ERASE functionality). 

I think it is better to collaborate on the same repository. 

I didn't ask for anything other than making my proposals to support more cards. 

I'm **quite disappointed** by the fork proposals but if it has to be like this I'm ready.

**Comment by julio-matarranz** [comment]
> > Sorry to ask but why mixing Han solo miner and Nerdminer in the same projet ?
> 
> Nerdminer was based on hansolominer code, I personally avoid forks in project, if 90% of code is similar why forking a codebase.
> 
> When @BitMaker-hub decided to fork it behaved in a strange way compared to the open source world (among other things repeated for the flasher, as you can see the fork still lacks the ERASE functionality).
> 
> I think it is better to collaborate on the same repository.
> 
> I didn't ask for anything other than making my proposals to support more cards.
> 
> I'm **quite disappointed** by the fork proposals but if it has to be like this I'm ready.

Thank you for your answer I understand your point and I think there is a commercial reason about the name... The fork with rename could have been avoided for sure.

**Comment by BitMaker-hub** [comment]
I fully agree with adding these cards and have no issue with them using the HANminer interface.

From the beginning, I have maintained that NerdMiner was based on Valerio's project, and I've tried to respect it fully. I've sought advice and aimed to be as respectful as possible in this regard. My intention was never otherwise, and I've been learning to work and collaborate in other repositories during this time. If I forked at the start instead of making a pull request (PR), it wasn't by my own choice at that time, but due to a lack of understanding of how the tools worked.

On my part, there was also no commercial intention; I always wanted to learn with this project and for people to like and know about it. The project's growth was driven purely by a passion for improvement and learning, which led me to invest so many hours into it and later, upon seeing others "commercialize" it, to do the same. If I have offended anyone, I apologize.

**Pull request merged**
