### PR TITLE
t-hmi platformio lib_deps fix dev build

### PR DESCRIPTION
**Pull request by cosmicpsyop**
discovered this only after clearing my workspace cache.

### CODE REVIEW

**Comment by julio-matarranz** [comment]
Dear,
Thanks I already fixed the dev branch before seeing your PR 😅

**Comment by julio-matarranz** [comment]
Eventually if you want to upgrade to latest stable version of mathertel/OneButton and run some tests it would be nice. Otherwise I would do it soon ☺️

**Comment by cosmicpsyop** [comment]
I'm happy to if you let me know the version I need to bump to.

**Comment by julio-matarranz** [comment]
> I'm happy to if you let me know the version I need to bump to.

You can find versions on platformio's registry https://registry.platformio.org/libraries/mathertel/OneButton

**Comment by cosmicpsyop** [comment]
i was just thinking of doing a github action for PRs and look at you.  you already started working it.  kewl
https://github.com/BitMaker-hub/NerdMiner_v2/pull/403

**Comment by julio-matarranz** [comment]
> i was just thinking of doing a github action for PRs and look at you.  you already started working it.  kewl
> 
> https://github.com/BitMaker-hub/NerdMiner_v2/pull/403

Yes introduced automatic prerelease on dev branch but it needs more access rights to work.

**Pull request closed without merging**
